-- 알람의 현재 상태 정본. Alert는 episode에서 사용자에게 통지한 개별 이벤트 이력이다.
ALTER TABLE sensor_channel
    ADD CONSTRAINT uk_sensor_channel_id_device UNIQUE (id, device_id);

CREATE TABLE alarm_episode (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alarm_type varchar(32) NOT NULL,
    scope_type varchar(16) NOT NULL,
    status varchar(16) NOT NULL,
    current_severity varchar(16) NOT NULL,
    max_severity varchar(16) NOT NULL,
    device_id bigint,
    channel_id bigint,
    zone_id bigint,
    opened_at timestamptz(6) NOT NULL,
    resolved_at timestamptz(6),
    resolution_reason varchar(32),
    last_notified_at timestamptz(6),
    evidence varchar(255),
    recommendation varchar(255),
    snapshot jsonb NOT NULL,
    legacy_backfill boolean NOT NULL DEFAULT false,
    created_at timestamptz(6) NOT NULL,
    updated_at timestamptz(6) NOT NULL,
    CONSTRAINT ck_alarm_episode_type
        CHECK (alarm_type IN ('THRESHOLD', 'DEVICE_SILENCE', 'ZONE_SILENCE')),
    CONSTRAINT ck_alarm_episode_scope_type
        CHECK (scope_type IN ('CHANNEL', 'DEVICE', 'ZONE')),
    CONSTRAINT ck_alarm_episode_status
        CHECK (status IN ('OPEN', 'RESOLVED')),
    CONSTRAINT ck_alarm_episode_severity
        CHECK (
            current_severity IN ('INFO', 'WARNING', 'CRITICAL')
            AND max_severity IN ('INFO', 'WARNING', 'CRITICAL')
        ),
    CONSTRAINT ck_alarm_episode_resolution_reason
        CHECK (resolution_reason IS NULL OR resolution_reason IN (
            'RECOVERED', 'CONFIG_CHANGED', 'PLANNED_OFFLINE', 'RESUME_GRACE',
            'RECLASSIFIED', 'MONITORING_DISABLED'
        )),
    CONSTRAINT ck_alarm_episode_scope CHECK (
        (alarm_type = 'THRESHOLD' AND scope_type = 'CHANNEL'
            AND device_id IS NOT NULL AND channel_id IS NOT NULL AND zone_id IS NULL)
        OR
        (alarm_type = 'DEVICE_SILENCE' AND scope_type = 'DEVICE'
            AND device_id IS NOT NULL AND channel_id IS NULL AND zone_id IS NULL)
        OR
        (alarm_type = 'ZONE_SILENCE' AND scope_type = 'ZONE'
            AND device_id IS NULL AND channel_id IS NULL AND zone_id IS NOT NULL)
    ),
    CONSTRAINT ck_alarm_episode_lifecycle CHECK (
        (status = 'OPEN' AND resolved_at IS NULL AND resolution_reason IS NULL)
        OR
        (status = 'RESOLVED' AND resolved_at IS NOT NULL
            AND resolution_reason IS NOT NULL AND resolved_at >= opened_at)
    ),
    CONSTRAINT fk_alarm_episode_device FOREIGN KEY (device_id) REFERENCES device (id),
    CONSTRAINT fk_alarm_episode_channel FOREIGN KEY (channel_id) REFERENCES sensor_channel (id),
    CONSTRAINT fk_alarm_episode_threshold_owner
        FOREIGN KEY (channel_id, device_id) REFERENCES sensor_channel (id, device_id),
    CONSTRAINT fk_alarm_episode_zone FOREIGN KEY (zone_id) REFERENCES zones (id)
);

-- PostgreSQL의 NULL-distinct 의미를 피하도록 활성 scope별 partial unique를 둔다.
CREATE UNIQUE INDEX uk_alarm_episode_open_threshold
    ON alarm_episode (channel_id)
    WHERE status = 'OPEN' AND alarm_type = 'THRESHOLD';
CREATE UNIQUE INDEX uk_alarm_episode_open_device_silence
    ON alarm_episode (device_id)
    WHERE status = 'OPEN' AND alarm_type = 'DEVICE_SILENCE';
CREATE UNIQUE INDEX uk_alarm_episode_open_zone_silence
    ON alarm_episode (zone_id)
    WHERE status = 'OPEN' AND alarm_type = 'ZONE_SILENCE';
CREATE INDEX idx_alarm_episode_status_opened
    ON alarm_episode (status, opened_at DESC);

CREATE TABLE alarm_acknowledgement (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode_id bigint NOT NULL,
    user_id bigint NOT NULL,
    ack_severity varchar(16) NOT NULL,
    created_at timestamptz(6) NOT NULL,
    CONSTRAINT ck_alarm_ack_severity
        CHECK (ack_severity IN ('INFO', 'WARNING', 'CRITICAL')),
    CONSTRAINT fk_alarm_ack_episode
        FOREIGN KEY (episode_id) REFERENCES alarm_episode (id) ON DELETE CASCADE,
    CONSTRAINT fk_alarm_ack_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_alarm_ack_episode_created
    ON alarm_acknowledgement (episode_id, created_at DESC);

-- channel_status는 episode 정본의 hot-path mirror이며 관측 역행 방지 시각을 함께 가진다.
ALTER TABLE channel_status
    ADD COLUMN last_evaluated_observed_at timestamptz(6),
    ADD COLUMN last_evaluated_batch_id bigint,
    ADD COLUMN active_episode_id bigint,
    ADD CONSTRAINT fk_channel_status_last_evaluated_batch
        FOREIGN KEY (last_evaluated_batch_id) REFERENCES measurement_batch (id),
    ADD CONSTRAINT fk_channel_status_active_episode
        FOREIGN KEY (active_episode_id) REFERENCES alarm_episode (id);

-- 배포 전 마지막 저장 판독을 cursor로 승격해 오래된 replay가 현재 상태를 바꾸지 않게 한다.
UPDATE channel_status cs
SET last_evaluated_observed_at = latest.observed_at,
    last_evaluated_batch_id = latest.batch_id
FROM (
    SELECT DISTINCT ON (sr.channel_id)
           sr.channel_id,
           mb.observed_at,
           mb.id AS batch_id
    FROM sensor_reading sr
    JOIN measurement_batch mb ON mb.id = sr.batch_id
    WHERE mb.observed_at IS NOT NULL
    ORDER BY sr.channel_id, mb.observed_at DESC, mb.id DESC
) latest
WHERE latest.channel_id = cs.channel_id;

-- 기존 in_alarm=true mirror만 legacy OPEN threshold episode로 승격한다.
INSERT INTO alarm_episode (
    alarm_type, scope_type, status, current_severity, max_severity,
    device_id, channel_id, opened_at, last_notified_at, snapshot, legacy_backfill,
    created_at, updated_at
)
SELECT
    'THRESHOLD', 'CHANNEL', 'OPEN',
    COALESCE(latest_alert.severity, 'WARNING'),
    COALESCE(latest_alert.severity, 'WARNING'),
    c.device_id, cs.channel_id,
    COALESCE(cs.last_alert_at, CURRENT_TIMESTAMP),
    cs.last_alert_at,
    jsonb_build_object(
        'deviceCode', d.code,
        'deviceName', d.name,
        'channelCode', c.code,
        'zoneName', z.name,
        'unit', c.unit,
        'quantityKind', c.quantity_kind,
        'thresholdValue', c.threshold_value,
        'thresholdDirection', c.threshold_direction,
        'openingValue', latest_alert.sensor_value
    ),
    true,
    COALESCE(cs.last_alert_at, CURRENT_TIMESTAMP),
    CURRENT_TIMESTAMP
FROM channel_status cs
JOIN sensor_channel c ON c.id = cs.channel_id
JOIN device d ON d.id = c.device_id
LEFT JOIN zones z ON z.id = d.zone_id
LEFT JOIN LATERAL (
    SELECT a.severity, a.sensor_value
    FROM alert a
    WHERE a.channel_id = cs.channel_id
    ORDER BY a.created_at DESC, a.id DESC
    LIMIT 1
) latest_alert ON true
WHERE cs.in_alarm = true;

UPDATE channel_status cs
SET active_episode_id = e.id
FROM alarm_episode e
WHERE e.alarm_type = 'THRESHOLD'
  AND e.status = 'OPEN'
  AND e.channel_id = cs.channel_id;

-- status가 없던 기존 설정행도 생성해 Wave 2의 FOR UPDATE 경계를 항상 보장한다.
INSERT INTO device_status (device_id, last_seen_at)
SELECT d.id, NULL
FROM device d
ON CONFLICT (device_id) DO NOTHING;

INSERT INTO channel_status (channel_id, in_alarm, last_alert_at)
SELECT c.id, false, NULL
FROM sensor_channel c
ON CONFLICT (channel_id) DO NOTHING;

-- 기존 Alert 필드를 보존하고 lifecycle/notification 분류만 additive하게 붙인다.
ALTER TABLE alert
    ADD COLUMN episode_id bigint,
    ADD COLUMN alarm_type varchar(32),
    ADD COLUMN scope_type varchar(16),
    ADD COLUMN notification_reason varchar(32),
    ADD COLUMN notification_status varchar(24) NOT NULL DEFAULT 'NOT_REQUESTED',
    ADD COLUMN notification_attempts integer NOT NULL DEFAULT 0,
    ADD COLUMN last_notification_attempt_at timestamptz(6),
    ADD COLUMN notified_at timestamptz(6),
    ADD COLUMN notification_error varchar(1000),
    ADD CONSTRAINT fk_alert_episode
        FOREIGN KEY (episode_id) REFERENCES alarm_episode (id) ON DELETE SET NULL,
    ADD CONSTRAINT ck_alert_notification_status
        CHECK (notification_status IN ('NOT_REQUESTED', 'PENDING', 'SENT', 'FAILED', 'SKIPPED')),
    ADD CONSTRAINT ck_alert_notification_attempts
        CHECK (notification_attempts >= 0);

UPDATE alert
SET alarm_type = CASE
        WHEN channel_id IS NOT NULL THEN 'THRESHOLD'
        WHEN message LIKE '구역 전체 수신 끊김%' THEN 'ZONE_SILENCE'
        ELSE 'DEVICE_SILENCE'
    END,
    scope_type = CASE
        WHEN channel_id IS NOT NULL THEN 'CHANNEL'
        WHEN message LIKE '구역 전체 수신 끊김%' THEN 'ZONE'
        ELSE 'DEVICE'
    END,
    notification_reason = 'LEGACY';

ALTER TABLE alert
    ALTER COLUMN alarm_type SET NOT NULL,
    ALTER COLUMN scope_type SET NOT NULL,
    ALTER COLUMN notification_reason SET NOT NULL,
    ADD CONSTRAINT ck_alert_alarm_type
        CHECK (alarm_type IN ('THRESHOLD', 'DEVICE_SILENCE', 'ZONE_SILENCE')),
    ADD CONSTRAINT ck_alert_scope_type
        CHECK (scope_type IN ('CHANNEL', 'DEVICE', 'ZONE')),
    ADD CONSTRAINT ck_alert_alarm_scope_pair
        CHECK (
            (alarm_type = 'THRESHOLD' AND scope_type = 'CHANNEL')
            OR (alarm_type = 'DEVICE_SILENCE' AND scope_type = 'DEVICE')
            OR (alarm_type = 'ZONE_SILENCE' AND scope_type = 'ZONE')
        ),
    ADD CONSTRAINT ck_alert_notification_reason
        CHECK (notification_reason IN ('INITIAL', 'REMINDER', 'SEVERITY_ESCALATION', 'LEGACY'));

-- V7을 모르는 이전 backend로 image rollback해도 기존 INSERT가 계속 동작하도록
-- 생략된 additive metadata를 DB 경계에서 legacy 값으로 보완한다.
CREATE OR REPLACE FUNCTION fill_legacy_alert_lifecycle_metadata()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.alarm_type IS NULL THEN
        NEW.alarm_type := CASE
            WHEN NEW.channel_id IS NOT NULL THEN 'THRESHOLD'
            WHEN NEW.message LIKE '구역 전체 수신 끊김%' THEN 'ZONE_SILENCE'
            ELSE 'DEVICE_SILENCE'
        END;
    END IF;
    IF NEW.scope_type IS NULL THEN
        NEW.scope_type := CASE
            WHEN NEW.channel_id IS NOT NULL THEN 'CHANNEL'
            WHEN NEW.message LIKE '구역 전체 수신 끊김%' THEN 'ZONE'
            ELSE 'DEVICE'
        END;
    END IF;
    IF NEW.notification_reason IS NULL THEN
        NEW.notification_reason := 'LEGACY';
    END IF;
    RETURN NEW;
END
$$;

CREATE TRIGGER trg_fill_legacy_alert_lifecycle_metadata
BEFORE INSERT ON alert
FOR EACH ROW
EXECUTE FUNCTION fill_legacy_alert_lifecycle_metadata();

CREATE INDEX idx_alert_episode_created
    ON alert (episode_id, created_at DESC);
CREATE INDEX idx_alert_notification_pending
    ON alert (notification_status, created_at)
    WHERE notification_status IN ('PENDING', 'FAILED');
