-- eventId는 producer 전역이 아니라 deviceCode 범위다. surrogate PK와 tuple unique를 함께 둔다.
CREATE TABLE ingest_receipt (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_code varchar(255) NOT NULL,
    event_id varchar(128) NOT NULL,
    request_hash varchar(128) NOT NULL,
    outcome varchar(32),
    http_status integer,
    response_json jsonb,
    created_at timestamptz(6) NOT NULL,
    CONSTRAINT uk_ingest_receipt_device_event UNIQUE (device_code, event_id),
    CONSTRAINT ck_ingest_receipt_outcome
        CHECK (outcome IS NULL OR outcome IN (
            'SAVED', 'DEVICE_NOT_FOUND', 'NO_KNOWN_CHANNELS', 'FUTURE_OBSERVED_AT'
        )),
    CONSTRAINT ck_ingest_receipt_completion CHECK (
        (outcome IS NULL AND http_status IS NULL AND response_json IS NULL)
        OR
        (outcome IS NOT NULL AND http_status IS NOT NULL AND response_json IS NOT NULL)
    )
);
CREATE INDEX idx_ingest_receipt_created
    ON ingest_receipt (created_at);

-- batch는 global eventId가 아니라 예약된 receipt surrogate id를 참조한다.
ALTER TABLE measurement_batch
    ADD COLUMN receipt_id bigint,
    ADD CONSTRAINT uk_measurement_batch_receipt UNIQUE (receipt_id),
    ADD CONSTRAINT fk_measurement_batch_receipt
        FOREIGN KEY (receipt_id) REFERENCES ingest_receipt (id);
